name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Sync
      run: cargo build --no-default-fefatures --features sync --verbose
    - name: Run Sync tests
      run: cargo test --no-default-fefatures --features sync --verbose
    - name: Build Async
      run: cargo build --no-default-fefatures --features async-tokio --verbose
    - name: Run Async tests
      run: cargo test --no-default-fefatures --features async-tokio --verbose
